version: "3.9"

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "4155:80"
    environment:
      spring_profiles_active: docker

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'servidor2'
      MYSQL_USER: 'servidor2'
      MYSQL_PASSWORD: 'servidor2'
      MYSQL_ROOT_PASSWORD: 'servidor2'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "3001:8080"
    depends_on:
      - db

volumes:
  data: